### ISSUE TITLE
TIG Stack may not work with influxdb:latest and telegraf:latest

### ISSUE THREAD

**Issue by jefcorco** [DataKnox/Cisco-MDT-TIG-Docker#1]
After cloning this repo, updating the telegraf.conf file with my PCs IP (192.1658.1.32), and running docker-compose, telegraf failed to connect to influxdb:

telegraf    | 2022-04-18T16:49:36Z W! [outputs.influxdb] When writing to [http://192.168.1.32:8086]: database "cisco_mdt" creation failed: 401 Unauthorized

I didn't dig into it but I suspect that authorization has changed with influx 2.x. I was able to quickly work around the issue by using some old docker images. I updated the docker-compose.yml to specify influxdb:183 and telegraf:1.16.1. I also removed the influxdb port "8083:8083", which didn't seem to be needed.

```
version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.3
    ports:
      - "8086:8086"
    volumes:
      - ./vols/:/var/lib/influxdb
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    links:
      - influxdb
    restart: always

  telegraf:
    container_name: telegraf
    image: telegraf:1.16.1
    ports:
      - "57000:57000"   
    links:
      - influxdb
    volumes:
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

```

This is a very nice TIG stack for Cisco MDT, so it would be great if it could be updated to work with the latest docker images.
